### ISSUE TITLE
Core::zip Documentation

### ISSUE THREAD

**Issue by NeuralCoder3** [AnyDSL/thorin2#167]
The [`%core.zip` axiom](https://github.com/fodinabor/thorin2/blob/feature/lower-zip/dialects/core/core.thorin#L214) needs better documentation.
A more high-level type scheme is
```
zip: 
∀ s:ℕʳ, Tᵢₙ:☆ⁿⁱ, Tₒᵤₜ:☆ⁿᵒ,
f: Tᵢₙ -> Tₒᵤₜ, // maps input tuple to output tuple
«i:nᵢ; «s; Tᵢₙ#i»» -> // input 
«o:nₒ; «s; Tₒᵤₜ#i»» -> // output 
```
Above, `Tᵢₙ` is used for `«i:nᵢ; Tᵢₙ#i»` when appropriate.

The input seems to be an array/tuple where each element has the array `s:ℕʳ` as dimension/size and all their elements have the type of `Tᵢₙ`.
This would be something like `input#i : (Tᵢₙ#i) array` (mixing a few notations for alternative presentations). Where `input#i` is an r-dimensional array and each entry `j` has size `s#j`.
However, I might misinterpret these dependent arrays.

A clean high-level explanation is needed:
* what is the concrete type (maybe also in Idris/Gallina notation)
* what does this axiom do

To me, this axiom seems more like a semi-polytypic map that lifts a function on the level of dependent tensors.
Whereas I would expect a zip to combine two data streams/sources/structures.

Note: Ideally, every axiom should come with a semantical specification as the axioms are only placeholders for a meaning that is rewritten in passes or instantiated at code generation. This might however be not possible to do compactly for every axiom or overload the declarations. (We also would need a unified way to specify semantics.)

**Comment by leissa** [comment]
The `zip` right now is more like a demo that we will likely remove in favor of other solutions like the `zip` from your matrix dialect. My intention was to have sth that we can use to "lift" scalar operations to also work on vectors similar to LLVM's vector/SIMD semantics - and since we are in the business of adding a "lift" operation we can also make it work for matrices, tensors, etc as well. But anyway, take the current thing with a grain of salt.
